version: "3.8"
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
    volumes:
      - data_mysql:/var/lib/mysql
volumes:
  data_mysql:
networks:
  mysql_network:
    name: mysql_network2
    driver: bridge
